// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 LabAcacia / INNO LOTUS PTY LTD
//
// NCP Error Codes — All v0.4 protocol error codes
// NPS-1 §6 + §7.4
//
// Implementation-only codes (NCP_FRAME_PARSE_ERROR, NCP_FRAME_INCOMPLETE) cover
// wire-layer parse failures not in spec §6. See test/ncp_test_results.md spec
// question 2 for the proposal to register them upstream.

export const NCP_ERROR_CODES = {
  // Implementation-only codes (not in spec §6 — see test_results.md spec question 2)
  NCP_FRAME_PARSE_ERROR: "NCP-FRAME-PARSE-ERROR",
  NCP_FRAME_INCOMPLETE: "NCP-FRAME-INCOMPLETE",
  // Spec-defined codes
  NCP_FRAME_UNKNOWN_TYPE: "NCP-FRAME-UNKNOWN-TYPE",
  NCP_FRAME_PAYLOAD_TOO_LARGE: "NCP-FRAME-PAYLOAD-TOO-LARGE",
  NCP_FRAME_FLAGS_INVALID: "NCP-FRAME-FLAGS-INVALID",
  NCP_ANCHOR_NOT_FOUND: "NCP-ANCHOR-NOT-FOUND",
  NCP_ANCHOR_SCHEMA_INVALID: "NCP-ANCHOR-SCHEMA-INVALID",
  NCP_ANCHOR_ID_MISMATCH: "NCP-ANCHOR-ID-MISMATCH",
  NCP_ANCHOR_STALE: "NCP-ANCHOR-STALE",
  NCP_STREAM_SEQ_GAP: "NCP-STREAM-SEQ-GAP",
  NCP_STREAM_NOT_FOUND: "NCP-STREAM-NOT-FOUND",
  NCP_STREAM_LIMIT_EXCEEDED: "NCP-STREAM-LIMIT-EXCEEDED",
  NCP_STREAM_WINDOW_OVERFLOW: "NCP-STREAM-WINDOW-OVERFLOW",
  NCP_ENCODING_UNSUPPORTED: "NCP-ENCODING-UNSUPPORTED",
  NCP_DIFF_FORMAT_UNSUPPORTED: "NCP-DIFF-FORMAT-UNSUPPORTED",
  NCP_VERSION_INCOMPATIBLE: "NCP-VERSION-INCOMPATIBLE",
  NCP_ENC_NOT_NEGOTIATED: "NCP-ENC-NOT-NEGOTIATED",
  NCP_ENC_AUTH_FAILED: "NCP-ENC-AUTH-FAILED",
} as const;

export type NcpErrorCode = typeof NCP_ERROR_CODES[keyof typeof NCP_ERROR_CODES];
