// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 LabAcacia / INNO LOTUS PTY LTD
//
// NPS native status codes — per spec/status-codes.md

/** NPS native status code constants. */
export const NpsStatusCodes = {
  // Success
  NPS_OK: "NPS-OK",
  NPS_OK_ACCEPTED: "NPS-OK-ACCEPTED",
  NPS_OK_NO_CONTENT: "NPS-OK-NO-CONTENT",

  // Auth
  NPS_AUTH_UNAUTHENTICATED: "NPS-AUTH-UNAUTHENTICATED",
  NPS_AUTH_FORBIDDEN: "NPS-AUTH-FORBIDDEN",

  // Client errors
  NPS_CLIENT_BAD_FRAME: "NPS-CLIENT-BAD-FRAME",
  NPS_CLIENT_BAD_PARAM: "NPS-CLIENT-BAD-PARAM",
  NPS_CLIENT_NOT_FOUND: "NPS-CLIENT-NOT-FOUND",
  NPS_CLIENT_CONFLICT: "NPS-CLIENT-CONFLICT",
  NPS_CLIENT_GONE: "NPS-CLIENT-GONE",
  NPS_CLIENT_UNPROCESSABLE: "NPS-CLIENT-UNPROCESSABLE",

  // Server errors
  NPS_SERVER_INTERNAL: "NPS-SERVER-INTERNAL",
  NPS_SERVER_UNAVAILABLE: "NPS-SERVER-UNAVAILABLE",
  NPS_SERVER_TIMEOUT: "NPS-SERVER-TIMEOUT",
  NPS_SERVER_ENCODING_UNSUPPORTED: "NPS-SERVER-ENCODING-UNSUPPORTED",

  // Stream
  NPS_STREAM_SEQ_GAP: "NPS-STREAM-SEQ-GAP",
  NPS_STREAM_NOT_FOUND: "NPS-STREAM-NOT-FOUND",
  NPS_STREAM_LIMIT: "NPS-STREAM-LIMIT",

  // Limit
  NPS_LIMIT_RATE: "NPS-LIMIT-RATE",
  NPS_LIMIT_BUDGET: "NPS-LIMIT-BUDGET",
  NPS_LIMIT_PAYLOAD: "NPS-LIMIT-PAYLOAD",
  NPS_LIMIT_EXCEEDED: "NPS-LIMIT-EXCEEDED",

  // Protocol
  NPS_PROTO_VERSION_INCOMPATIBLE: "NPS-PROTO-VERSION-INCOMPATIBLE",
} as const;

export type NpsStatusCode = (typeof NpsStatusCodes)[keyof typeof NpsStatusCodes];
